namespace api.Classes
{
    public class PlayerImage
    {
        public required string Puuid { get; set; }
        public double Champion_1 { get; set; }
        public double Champion_2 { get; set; }
        public double Champion_3 { get; set; }
        public double Champion_4 { get; set; }
        public double Champion_5 { get; set; }
        public double Champion_6 { get; set; }
        public double Champion_7 { get; set; }
        public double Champion_8 { get; set; }
        public double Champion_9 { get; set; }
        public double Champion_10 { get; set; }
        public double Champion_11 { get; set; }
        public double Champion_12 { get; set; }
        public double Champion_13 { get; set; }
        public double Champion_14 { get; set; }
        public double Champion_15 { get; set; }
        public double Champion_16 { get; set; }
        public double Champion_17 { get; set; }
        public double Champion_18 { get; set; }
        public double Champion_19 { get; set; }
        public double Champion_20 { get; set; }
        public double Champion_21 { get; set; }
        public double Champion_22 { get; set; }
        public double Champion_23 { get; set; }
        public double Champion_24 { get; set; }
        public double Champion_25 { get; set; }
        public double Champion_26 { get; set; }
        public double Champion_27 { get; set; }
        public double Champion_28 { get; set; }
        public double Champion_29 { get; set; }
        public double Champion_30 { get; set; }
        public double Champion_31 { get; set; }
        public double Champion_32 { get; set; }
        public double Champion_33 { get; set; }
        public double Champion_34 { get; set; }
        public double Champion_35 { get; set; }
        public double Champion_36 { get; set; }
        public double Champion_37 { get; set; }
        public double Champion_38 { get; set; }
        public double Champion_39 { get; set; }
        public double Champion_40 { get; set; }
        public double Champion_41 { get; set; }
        public double Champion_42 { get; set; }
        public double Champion_43 { get; set; }
        public double Champion_44 { get; set; }
        public double Champion_45 { get; set; }
        public double Champion_46 { get; set; }
        public double Champion_47 { get; set; }
        public double Champion_48 { get; set; }
        public double Champion_49 { get; set; }
        public double Champion_50 { get; set; }
        public double Champion_51 { get; set; }
        public double Champion_52 { get; set; }
        public double Champion_53 { get; set; }
        public double Champion_54 { get; set; }
        public double Champion_55 { get; set; }
        public double Champion_56 { get; set; }
        public double Champion_57 { get; set; }
        public double Champion_58 { get; set; }
        public double Champion_59 { get; set; }
        public double Champion_60 { get; set; }
        public double Champion_61 { get; set; }
        public double Champion_62 { get; set; }
        public double Champion_63 { get; set; }
        public double Champion_64 { get; set; }
        public double Champion_65 { get; set; }
        public double Champion_66 { get; set; }
        public double Champion_67 { get; set; }
        public double Champion_68 { get; set; }
        public double Champion_69 { get; set; }
        public double Champion_70 { get; set; }
        public double Champion_71 { get; set; }
        public double Champion_72 { get; set; }
        public double Champion_73 { get; set; }
        public double Champion_74 { get; set; }
        public double Champion_75 { get; set; }
        public double Champion_76 { get; set; }
        public double Champion_77 { get; set; }
        public double Champion_78 { get; set; }
        public double Champion_79 { get; set; }
        public double Champion_80 { get; set; }
        public double Champion_81 { get; set; }
        public double Champion_82 { get; set; }
        public double Champion_83 { get; set; }
        public double Champion_84 { get; set; }
        public double Champion_85 { get; set; }
        public double Champion_86 { get; set; }
        public double Champion_87 { get; set; }
        public double Champion_88 { get; set; }
        public double Champion_89 { get; set; }
        public double Champion_90 { get; set; }
        public double Champion_91 { get; set; }
        public double Champion_92 { get; set; }
        public double Champion_93 { get; set; }
        public double Champion_94 { get; set; }
        public double Champion_95 { get; set; }
        public double Champion_96 { get; set; }
        public double Champion_97 { get; set; }
        public double Champion_98 { get; set; }
        public double Champion_99 { get; set; }
        public double Champion_100 { get; set; }
        public double Champion_101 { get; set; }
        public double Champion_102 { get; set; }
        public double Champion_103 { get; set; }
        public double Champion_104 { get; set; }
        public double Champion_105 { get; set; }
        public double Champion_106 { get; set; }
        public double Champion_107 { get; set; }
        public double Champion_108 { get; set; }
        public double Champion_109 { get; set; }
        public double Champion_110 { get; set; }
        public double Champion_111 { get; set; }
        public double Champion_112 { get; set; }
        public double Champion_113 { get; set; }
        public double Champion_114 { get; set; }
        public double Champion_115 { get; set; }
        public double Champion_116 { get; set; }
        public double Champion_117 { get; set; }
        public double Champion_118 { get; set; }
        public double Champion_119 { get; set; }
        public double Champion_120 { get; set; }
        public double Champion_121 { get; set; }
        public double Champion_122 { get; set; }
        public double Champion_123 { get; set; }
        public double Champion_124 { get; set; }
        public double Champion_125 { get; set; }
        public double Champion_126 { get; set; }
        public double Champion_127 { get; set; }
        public double Champion_128 { get; set; }
        public double Champion_129 { get; set; }
        public double Champion_130 { get; set; }
        public double Champion_131 { get; set; }
        public double Champion_132 { get; set; }
        public double Champion_133 { get; set; }
        public double Champion_134 { get; set; }
        public double Champion_135 { get; set; }
        public double Champion_136 { get; set; }
        public double Champion_137 { get; set; }
        public double Champion_138 { get; set; }
        public double Champion_139 { get; set; }
        public double Champion_140 { get; set; }
        public double Champion_141 { get; set; }
        public double Champion_142 { get; set; }
        public double Champion_143 { get; set; }
        public double Champion_144 { get; set; }
        public double Champion_145 { get; set; }
        public double Champion_146 { get; set; }
        public double Champion_147 { get; set; }
        public double Champion_148 { get; set; }
        public double Champion_149 { get; set; }
        public double Champion_150 { get; set; }
        public double Champion_151 { get; set; }
        public double Champion_152 { get; set; }
        public double Champion_153 { get; set; }
        public double Champion_154 { get; set; }
        public double Champion_155 { get; set; }
        public double Champion_156 { get; set; }
        public double Champion_157 { get; set; }
        public double Champion_158 { get; set; }
        public double Champion_159 { get; set; }
        public double Champion_160 { get; set; }
        public double Champion_161 { get; set; }
        public double Champion_162 { get; set; }
        public double Champion_163 { get; set; }
        public double Champion_164 { get; set; }
        public double Champion_165 { get; set; }
        public double Champion_166 { get; set; }
        public double Champion_167 { get; set; }
        public double Champion_168 { get; set; }
    } 
}